<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeepSpace.Domain\DeepSpace.Domain.csproj" />
    <ProjectReference Include="..\DeepSpace.Engine\DeepSpace.Engine.csproj" />
    <ProjectReference Include="..\DeepSpace.Persistence\DeepSpace.Persistence.csproj" />
  </ItemGroup>

</Project>
